name: Vishnu First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello Vishnu."
      - name: Print Good Bye
        run: echo "Done - Bye!"
      - name: Multi Line Run Command
        run: |
          echo "This is the first line."
          echo "This is the second line."
          pwd
