name: Hello World Workflow

on:
    push:
        branches:
            - main
            - develop

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Print Hello World
              run: echo "Hello World"