name: Hello World Workflow

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Output Parameters
              run: echo "CLIENT_ID/:${{vars.AZ_SPN_CLIENT_ID}}"